sudo : false

cache: 
  directories:
    - programs

notifications:
  email: false
language: cpp
compiler:
  - clang

before_install:
    - ./scripts/set_cache.sh
    - export PATH=$PWD/programs/cmake/bin:$PATH
    - export PATH=$PWD/programs/ninja:$PATH
    - export DEAL_II_DIR=$PWD/programs/dealii/home/travis/dealii-inst
    - export PATH=$PWD/programs/astyle/build/gcc/bin:$PATH

script:
    - mkdir build
    - cd build
    - echo $PATH
    - cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/travis/dealii-sak-inst ..
    - ninja -j4 install
    - tar cvfz /home/travis/dealii-sak-CI-build.tgz /home/travis/dealii-sak-inst
    - ctest -j4 -V
    - cd ..; ./scripts/check_indentation.sh

deploy:
  provider: releases
  api_key:
    secure: JBIOZ2GRmxWduUKtM6E623y4lju4P7nKsa+DYh2qwrlSqQDrDoRPwGt9LW8T8l9CiMhvKbXTdzEsmQMdtHGzRW2GV9VU/lsugMTEGJMtjd/ly0dwTyscBhnBudLnk/z1lZB/wKgxi2r+fmsthRctvtzkIK8uRBqA0ivkAD9wFRU=
  file: /home/travis/dealii-sak-CI-build.tgz
  skip_cleanup: true
  on:
    repo: luca-heltai/dealii-sak
    tags: true
    all_branches: true

