sudo : false
notifications:
  email: false
language: cpp
compiler:
- clang
before_install:
    - mkdir programs
    - wget http://www.cmake.org/files/v3.3/cmake-3.3.0-rc3-Linux-x86_64.tar.gz
    - tar xzf cmake-3.3.0-rc3-Linux-x86_64.tar.gz -C programs
    - rm cmake-3.3.0-rc3-Linux-x86_64.tar.gz
    - mv programs/cmake-* programs/cmake
    - export PATH=$PWD/programs/cmake/bin:$PATH
    - cd programs
    - git clone git://github.com/martine/ninja.git
    - cd ninja
    - git checkout release
    - ./configure.py --bootstrap
    - export PATH=$PWD:$PATH
    - cd ../..
    - export D2V=`git ls-remote --tags https://github.com/luca-heltai/dealii | tail -n 1 | awk -F"/" '{print $3}'`
    - echo "Deal.II version $D2V"
    - wget https://github.com/luca-heltai/dealii/releases/download/$D2V/dealii-travis-CI-build.tgz
    - tar xfz dealii-travis-CI-build.tgz -C /
    - ./scripts/setup_astyle.sh
script:
    - mkdir build
    - cd build
    - export DEAL_II_DIR=~/dealii-inst
    - cmake -GNinja -DCMAKE_INSTALL_PREFIX=~/dealii-sak-inst ..
    - ninja -j4 install
    - tar cvfz /home/travis/dealii-sak-CI-build.tgz /home/travis/dealii-sak-inst
    - ctest -j4 -V
    - cd ..; ./scripts/check_indentation.sh
deploy:
  provider: releases
  api_key:
    secure: JBIOZ2GRmxWduUKtM6E623y4lju4P7nKsa+DYh2qwrlSqQDrDoRPwGt9LW8T8l9CiMhvKbXTdzEsmQMdtHGzRW2GV9VU/lsugMTEGJMtjd/ly0dwTyscBhnBudLnk/z1lZB/wKgxi2r+fmsthRctvtzkIK8uRBqA0ivkAD9wFRU=
  file: /home/travis/dealii-sak-CI-build.tgz
  skip_cleanup: true
  on:
    repo: luca-heltai/dealii-sak
    tags: true
    all_branches: true
