notifications:
  email: false
language: cpp
compiler:
- clang
before_install:
    - sudo apt-get install build-essential
    - sudo add-apt-repository -y ppa:kalakris/cmake
    - sudo add-apt-repository -y ppa:saiarcot895/chromium-beta
    - sudo apt-get update -qq
    - sudo apt-get install cmake
    - sudo apt-get install ninja-build
    - wget https://github.com/luca-heltai/dealii/releases/download/v8.3.pre.5/dealii-travis-CI-build.tgz
    - tar xfz dealii-travis-CI-build.tgz -C /
script:
    - mkdir build
    - cd build
    - export DEAL_II_DIR=/home/travis/dealii-inst
    - cmake -GNinja -DCMAKE_INSTALL_PREFIX=/home/travis/dealii-sak-inst ..
    - ninja -j4 install && ninja -j4 setup_tests && ctest -j4
    - tar cvfz /home/travis/dealii-sak-CI-build.tgz /home/travis/dealii-sak-inst
deploy:
  provider: releases
  api_key:
    secure: JBIOZ2GRmxWduUKtM6E623y4lju4P7nKsa+DYh2qwrlSqQDrDoRPwGt9LW8T8l9CiMhvKbXTdzEsmQMdtHGzRW2GV9VU/lsugMTEGJMtjd/ly0dwTyscBhnBudLnk/z1lZB/wKgxi2r+fmsthRctvtzkIK8uRBqA0ivkAD9wFRU=
  file: /home/travis/dealii-sak-CI-build.tgz
  skip_cleanup: true
  on:
    repo: luca-heltai/dealii-sak
    tags: true
    all_branches: true
