language: cpp
compiler:
- gcc
script:
    uname -a > /home/travis/test.txt
deploy:
  provider: releases
  api_key:
    secure: JBIOZ2GRmxWduUKtM6E623y4lju4P7nKsa+DYh2qwrlSqQDrDoRPwGt9LW8T8l9CiMhvKbXTdzEsmQMdtHGzRW2GV9VU/lsugMTEGJMtjd/ly0dwTyscBhnBudLnk/z1lZB/wKgxi2r+fmsthRctvtzkIK8uRBqA0ivkAD9wFRU=
  file: /home/travis/test.txt
  skip_cleanup: true
  on:
    repo: luca-heltai/dealii-sak
    tags: true
    all_branches: true
